Repository UMC-6th-BAB/BAB-BE, pull requests merged in 2024-08, with the labels that each got.

#39 [feat] 가게 삭제하기 api
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/entity/Store.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :sparkles: 기능

#41 [FEAT] 오늘의 할인 가게 페이지 API 구현
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/converter/StoreDtoConverter.java
  src/main/java/Bob_BE/domain/store/dto/parameter/StoreParameterDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/repository/StoreCustomRepository.java
  src/main/java/Bob_BE/domain/store/repository/StoreCustomRepositoryImpl.java
  src/main/java/Bob_BE/domain/store/repository/StoreRepository.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/domain/storeUniversity/repository/StoreUniversityRepository.java
  src/main/java/Bob_BE/domain/university/repository/UniversityRepository.java
Labels: :sparkles: 기능

#52 [FIX] 대표메뉴 엔티티 추가 및 방향 설정
  src/main/java/Bob_BE/domain/menu/entity/Menu.java
  src/main/java/Bob_BE/domain/signatureMenu/entity/SignatureMenu.java
  src/main/java/Bob_BE/domain/store/entity/Store.java
Labels: :zap: 수정

#50 [Feat] 가게 운영시간 등록하기, 수정하기
  src/main/java/Bob_BE/domain/operatingHours/converter/OperatingHoursConverter.java
  src/main/java/Bob_BE/domain/operatingHours/dto/request/OHRequestDto.java
  src/main/java/Bob_BE/domain/operatingHours/dto/response/OHResponseDto.java
  src/main/java/Bob_BE/domain/operatingHours/entity/OperatingHours.java
  src/main/java/Bob_BE/domain/operatingHours/repository/OperatingHoursRepository.java
  src/main/java/Bob_BE/domain/operatingHours/service/OperatingHoursService.java
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#54 [FEAT] 가게 상세 페이지 API 구현
  src/main/java/Bob_BE/domain/discount/entity/Discount.java
  src/main/java/Bob_BE/domain/menu/service/MenuService.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/converter/StoreDtoConverter.java
  src/main/java/Bob_BE/domain/store/dto/parameter/StoreParameterDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :sparkles: 기능

#56 [FEAT] 지도 핑을 위한 데이터 가져오기 API 구현
  src/main/java/Bob_BE/domain/discountMenu/repository/DiscountMenuCustomRepository.java
  src/main/java/Bob_BE/domain/discountMenu/repository/DiscountMenuCustomRepositoryImpl.java
  src/main/java/Bob_BE/domain/discountMenu/repository/DiscountMenuRepository.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/converter/StoreDtoConverter.java
  src/main/java/Bob_BE/domain/store/dto/parameter/StoreParameterDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :sparkles: 기능

#64 [FEAT] 배포파일 작성
  .github/workflows/dev-deploy.yml
  Dockerfile
Labels: :green_heart: CI/CD

#69 [FIX] URL 변경 완료
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
Labels: :zap: 수정

#72 [FEAT] 사장님 마이페이지 API 구현
  src/main/java/Bob_BE/domain/owner/controller/OwnerController.java
  src/main/java/Bob_BE/domain/owner/converter/OwnerConverter.java
  src/main/java/Bob_BE/domain/owner/converter/OwnerDtoConverter.java
  src/main/java/Bob_BE/domain/owner/dto/parameter/OwnerParameterDto.java
  src/main/java/Bob_BE/domain/owner/dto/request/OwnerRequestDto.java
  src/main/java/Bob_BE/domain/owner/dto/response/OwnerResponseDto.java
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/store/repository/StoreRepository.java
Labels: :sparkles: 기능

#75 [Feat] 시그니처 메뉴 등록 로직 추가
  src/main/java/Bob_BE/domain/menu/converter/MenuConverter.java
  src/main/java/Bob_BE/domain/menu/dto/request/MenuRequestDto.java
  src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/Bob_BE/domain/signatureMenu/repository/SignatureMenuRepository.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#79 [FEAT] CORS Filter 추가
  src/main/java/Bob_BE/global/config/CorsConfig.java
Labels: :sparkles: 기능

#91 [FIX]: 카카오 소셜 로그인 수정
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
  src/main/java/Bob_BE/global/external/KakaoAuthClient.java
  src/main/java/Bob_BE/global/external/KakaoResponseDto.java
  src/main/java/Bob_BE/global/external/KakaoUserClient.java
Labels: :sparkles: 기능, :zap: 수정

#96 [Fix]: JWT Role 추가
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
  src/main/java/Bob_BE/global/util/JwtTokenProvider.java
Labels: :sparkles: 기능, :zap: 수정

#97 fix: 오늘의 할인식당 식당기준으로 그룹화
  src/main/java/Bob_BE/domain/store/repository/StoreCustomRepository.java
  src/main/java/Bob_BE/domain/store/repository/StoreCustomRepositoryImpl.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
Labels: :sparkles: 기능, :zap: 수정

#101 [FEAT] SSL 인증파일 추가
  src/main/resources/ssl/keystore.p12
Labels: :sparkles: 기능

#111 [Refactor] 사업자 등록증 등록
  Dockerfile
Labels: :zap: 수정

#113 Fix#112 사장 학생 로그인 응답 수정
  src/main/java/Bob_BE/domain/owner/dto/response/OwnerResponseDto.java
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/student/dto/response/StudentResponseDto.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
Labels: :sparkles: 기능, :zap: 수정

#118 [REFACTOR] banner entity 수정
  src/main/java/Bob_BE/domain/banner/entity/Banner.java
  src/main/java/Bob_BE/domain/store/entity/Store.java
Labels: :recycle: 리팩터링

#117 [FIX] 지도 마커를 위한 데이터 가져오기 API 수정
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :zap: 수정

#122 [FIX] discount fix
  src/main/java/Bob_BE/domain/discount/repository/DiscountRepository.java
  src/main/java/Bob_BE/domain/discount/service/DiscountService.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
Labels: :zap: 수정

#125 Fix/#123 banner image upload
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :zap: 수정

#114 Feat/#76 search menu api
  build.gradle
  src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/dto/parameter/StoreParameterDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/repository/StoreRepository.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
  src/main/java/Bob_BE/domain/university/entity/University.java
  src/main/java/Bob_BE/domain/university/service/UniversityService.java
  src/main/java/Bob_BE/global/config/RedisConfig.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
  src/main/java/Bob_BE/global/response/exception/handler/StudentHandler.java
  src/main/java/Bob_BE/global/util/DataInitializer.java
Labels: :sparkles: 기능

#135 fix redis config
  Dockerfile
  src/main/java/Bob_BE/global/config/RedisConfig.java
Labels: :zap: 수정

#144 [FIX] 가게 정보 가져오기 수
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
Labels: :zap: 수정

#147 [FIX] 가게 정보에서 가게 링크 가져오기 추가
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
Labels: :zap: 수정

#153 fix: 사장 로그인 응답 수정
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
Labels: :sparkles: 기능, :zap: 수정

#156 [FIX] 마커 api 로직 수정
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/domain/university/repository/UniversityRepository.java
Labels: :sparkles: 기능, :zap: 수정
