Repository UMC-6th-BAB/BAB-BE, pull requests merged in 2024-07, with the labels that each got.

#2 [SETTING] 엔티티 생성
  src/main/java/Bob_BE/BabApplication.java
  src/main/java/Bob_BE/domain/alarm/entity/Alarm.java
  src/main/java/Bob_BE/domain/banner/entity/Banner.java
  src/main/java/Bob_BE/domain/discount/entity/Discount.java
  src/main/java/Bob_BE/domain/menu/entity/Menu.java
  src/main/java/Bob_BE/domain/operatingHours/entity/DayOfWeek.java
  src/main/java/Bob_BE/domain/operatingHours/entity/OperatingHours.java
  src/main/java/Bob_BE/domain/owner/entity/Owner.java
  src/main/java/Bob_BE/domain/store/entity/Store.java
  src/main/java/Bob_BE/domain/storeUniversity/entity/StoreUniversity.java
  src/main/java/Bob_BE/domain/student/entity/Student.java
  src/main/java/Bob_BE/domain/university/entity/University.java
  src/main/java/Bob_BE/global/baseEntity/BaseEntity.java
  src/main/resources/application.yml
Labels: :wrench: 설정

#9 [Setting] swagger, map struct, queryDsl 설정 추가
  build.gradle
  src/main/java/Bob_BE/global/queryDsl/QueryDslConfig.java
  src/main/java/Bob_BE/global/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :wrench: 설정

#5 [Feat] 학생 소셜 로그인, 회원가입 기능
  build.gradle
  gradlew
  src/main/java/Bob_BE/BabApplication.java
  src/main/java/Bob_BE/domain/student/controller/StudentController.java
  src/main/java/Bob_BE/domain/student/dto/request/StudentRequestDto.java
  src/main/java/Bob_BE/domain/student/dto/response/StudentResponseDto.java
  src/main/java/Bob_BE/domain/student/entity/Student.java
  src/main/java/Bob_BE/domain/student/repository/StudentRepository.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
  src/main/java/Bob_BE/domain/student/util/JwtTokenProvider.java
  src/main/java/Bob_BE/global/config/QueryDslConfig.java
  src/main/java/Bob_BE/global/config/SwaggerConfig.java
  src/main/java/Bob_BE/global/external/KakaoResponseDto.java
  src/main/java/Bob_BE/global/external/KakaoUserClient.java
  src/main/java/Bob_BE/global/response/code/resultCode/SuccessStatus.java
  src/main/resources/application.yml
Labels: :sparkles: 기능

#10 Feat/#4 메뉴 api 엔드포인트 매핑
  src/main/java/Bob_BE/domain/menu/controller/MenuController.java
  src/main/java/Bob_BE/domain/menu/converter/MenuConverter.java
  src/main/java/Bob_BE/domain/menu/dto/request/MenuRequestDto.java
  src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/Bob_BE/domain/menu/entity/Menu.java
  src/main/java/Bob_BE/domain/menu/repository/MenuRepository.java
  src/main/java/Bob_BE/domain/menu/service/MenuService.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/repository/StoreRepository.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
  src/main/java/Bob_BE/global/response/exception/handler/MenuHandler.java
  src/main/resources/application.yml
Labels: :sparkles: 기능

#15 [FEAT] 할인 추가 API 구현
  src/main/java/Bob_BE/domain/discount/controller/DiscountController.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountConverter.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountDtoConverter.java
  src/main/java/Bob_BE/domain/discount/dto/data/DiscountDataDto.java
  src/main/java/Bob_BE/domain/discount/dto/parameter/DiscountParameterDto.java
  src/main/java/Bob_BE/domain/discount/dto/request/DiscountRequestDto.java
  src/main/java/Bob_BE/domain/discount/dto/response/DiscountResponseDto.java
  src/main/java/Bob_BE/domain/discount/entity/Discount.java
  src/main/java/Bob_BE/domain/discount/repository/DiscountRepository.java
  src/main/java/Bob_BE/domain/discount/service/DiscountService.java
  src/main/java/Bob_BE/domain/discountMenu/converter/DiscountMenuConverter.java
  src/main/java/Bob_BE/domain/discountMenu/dto/data/DiscountMenuDataDto.java
  src/main/java/Bob_BE/domain/discountMenu/entity/DiscountMenu.java
  src/main/java/Bob_BE/domain/menu/entity/Menu.java
  src/main/java/Bob_BE/global/config/QueryDslConfig.java
  src/main/java/Bob_BE/global/config/SwaggerConfig.java
  src/main/java/Bob_BE/global/response/exception/handler/DiscountHandler.java
  src/main/java/Bob_BE/global/response/exception/handler/StoreHandler.java
Labels: :sparkles: 기능

#16 [FEAT] 할인 삭제 API 구현
  src/main/java/Bob_BE/BabApplication.java
  src/main/java/Bob_BE/domain/discount/controller/DiscountController.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountConverter.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountDtoConverter.java
  src/main/java/Bob_BE/domain/discount/dto/parameter/DiscountParameterDto.java
  src/main/java/Bob_BE/domain/discount/dto/response/DiscountResponseDto.java
  src/main/java/Bob_BE/domain/discount/service/DiscountService.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#17 [FEAT] 과거 할인했던 행사 목록 가져오기 API 구현
  src/main/java/Bob_BE/domain/discount/controller/DiscountController.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountConverter.java
  src/main/java/Bob_BE/domain/discount/converter/DiscountDtoConverter.java
  src/main/java/Bob_BE/domain/discount/dto/data/DiscountDataDto.java
  src/main/java/Bob_BE/domain/discount/dto/parameter/DiscountParameterDto.java
  src/main/java/Bob_BE/domain/discount/dto/response/DiscountResponseDto.java
  src/main/java/Bob_BE/domain/discount/repository/DiscountRepository.java
  src/main/java/Bob_BE/domain/discount/service/DiscountService.java
Labels: :sparkles: 기능

#22 [FEAT] 메뉴 관련 - API SWAGGER 작성
  src/main/java/Bob_BE/domain/menu/controller/MenuController.java
  src/main/java/Bob_BE/domain/menu/converter/MenuConverter.java
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
Labels: :sparkles: 기능

#21 [SETTING] S3 관련파일 추가
  build.gradle
  src/main/java/Bob_BE/global/config/S3Config.java
  src/main/resources/application.yml
Labels: :wrench: 설정

#24 [Feat] 가게 등록하기 API
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/converter/StoreConverter.java
  src/main/java/Bob_BE/domain/store/dto/request/StoreRequestDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/domain/storeUniversity/repository/StoreUniversityRepository.java
  src/main/java/Bob_BE/domain/storeUniversity/service/StoreUniversityService.java
  src/main/java/Bob_BE/domain/university/repository/UniversityRepository.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
  src/main/java/Bob_BE/global/response/exception/handler/OwnerHandler.java
  src/main/java/Bob_BE/global/response/exception/handler/UniversityHandler.java
Labels: :sparkles: 기능

#26 [Fix][Student, Owner Transaction 어노테이션 추가]
  src/main/java/Bob_BE/domain/owner/service/OwnerService.java
  src/main/java/Bob_BE/domain/student/service/StudentService.java
Labels: :recycle: 리팩터링

#28 [REFACTOR] dto 구조 변경
  src/main/java/Bob_BE/domain/discount/converter/DiscountConverter.java
  src/main/java/Bob_BE/domain/discount/dto/data/DiscountDataDto.java
  src/main/java/Bob_BE/domain/discount/dto/parameter/DiscountParameterDto.java
  src/main/java/Bob_BE/domain/discount/dto/request/DiscountRequestDto.java
  src/main/java/Bob_BE/domain/discount/dto/response/DiscountResponseDto.java
  src/main/java/Bob_BE/domain/discountMenu/dto/data/DiscountMenuDataDto.java
Labels: :recycle: 리팩터링

#32 [FIX] Store, Discount 방향수정
  src/main/java/Bob_BE/domain/store/entity/Store.java
Labels: :zap: 수정

#30 [Feat] 가게 정보 수정하기
  src/main/java/Bob_BE/domain/store/controller/StoreController.java
  src/main/java/Bob_BE/domain/store/dto/request/StoreRequestDto.java
  src/main/java/Bob_BE/domain/store/dto/response/StoreResponseDto.java
  src/main/java/Bob_BE/domain/store/entity/Store.java
  src/main/java/Bob_BE/domain/store/service/StoreService.java
  src/main/java/Bob_BE/domain/storeUniversity/entity/StoreUniversity.java
  src/main/java/Bob_BE/domain/storeUniversity/repository/StoreUniversityRepository.java
  src/main/java/Bob_BE/domain/storeUniversity/service/StoreUniversityService.java
Labels: :sparkles: 기능

#34 [FEAT] S3 이미지 업로드 기능 구현
  .github/ISSUE_TEMPLATE/기능-개발-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/기능-수정-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  .github/pull_request_template.md
  build.gradle
  src/main/java/Bob_BE/domain/menu/controller/MenuController.java
  src/main/java/Bob_BE/domain/menu/converter/MenuConverter.java
  src/main/java/Bob_BE/domain/menu/dto/response/ImageUploadResponseDto.java
  src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/Bob_BE/domain/menu/service/MenuService.java
  src/main/java/Bob_BE/global/response/code/resultCode/ErrorStatus.java
  src/main/java/Bob_BE/global/util/aws/S3StorageService.java
  src/main/java/Bob_BE/global/util/aws/StorageService.java
  src/main/resources/application.yml
Labels: :sparkles: 기능

#36 [FIX] 대학교 로고 추가
  src/main/java/Bob_BE/domain/university/entity/University.java
Labels: :zap: 수정
